FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["LW.Client/LW.Client.csproj", "LW.Client/"]
RUN dotnet restore "LW.Client/LW.Client.csproj"
COPY . .
WORKDIR "/src/LW.Client"
RUN dotnet build "LW.Client.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LW.Client.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf